export default {
  "version": 1,
  "products": {
    "sv10|pack": {
      "name": "Booster Pack",
      "setId": "sv10",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv10.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/destined-rivals/SV10_Booster_Cynthia_Garchomp.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv09|pack": {
      "name": "Booster Pack",
      "setId": "sv09",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv09.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/journey-together/journey-together-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv08|pack": {
      "name": "Booster Pack",
      "setId": "sv08",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv08.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/surging-sparks/SV8_Booster_Pikachu.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv07|pack": {
      "name": "Booster Pack",
      "setId": "sv07",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv07.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/stellar-crown/SV7_Booster_Terapagos.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv06.5|pack": {
      "name": "Booster Pack",
      "setId": "sv06.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv06.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/shrouded-fable/shrouded-fable-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv06|pack": {
      "name": "Booster Pack",
      "setId": "sv06",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv06.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/twilight-masquerade/SV6_Booster_Sinistcha.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv05|pack": {
      "name": "Booster Pack",
      "setId": "sv05",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv05.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/temporal-forces/SV5_Booster_Walking_Wake.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv04.5|pack": {
      "name": "Booster Pack",
      "setId": "sv04.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv04.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/paldean-fates/paldean-fates-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv04|pack": {
      "name": "Booster Pack",
      "setId": "sv04",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv04.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/paradox-rift/SV4_Booster_Garchomp.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv03.5|pack": {
      "name": "Booster Pack",
      "setId": "sv03.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv03.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/151/151-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv03|pack": {
      "name": "Booster Pack",
      "setId": "sv03",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv03.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/obsidian-flames/SV3_Booster_Revavroom.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv02|pack": {
      "name": "Booster Pack",
      "setId": "sv02",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv02.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/paldea-evolved/SV2_Booster_Ting-Lu.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sv01|pack": {
      "name": "Booster Pack",
      "setId": "sv01",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sv01.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/scarlet-and-violet/scarlet-and-violet-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh12.5|pack": {
      "name": "Booster Pack",
      "setId": "swsh12.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh12.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/crown-zenith/crown-zenith-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh12|pack": {
      "name": "Booster Pack",
      "setId": "swsh12",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh12.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/silver-tempest/SWSH12_Booster_Regidrago.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh11|pack": {
      "name": "Booster Pack",
      "setId": "swsh11",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh11.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/lost-origin/lost-origin-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh10|pack": {
      "name": "Booster Pack",
      "setId": "swsh10",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh10.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/astral-radiance/astral-radiance-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh9|pack": {
      "name": "Booster Pack",
      "setId": "swsh9",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh9.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/brilliant-stars/SWSH9_Booster_Whimsicott.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh8|pack": {
      "name": "Booster Pack",
      "setId": "swsh8",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh8.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/fusion-strike/SWSH8_Booster_Boltund.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh7|pack": {
      "name": "Booster Pack",
      "setId": "swsh7",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh7.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/evolving-skies/evolving-skies-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh6|pack": {
      "name": "Booster Pack",
      "setId": "swsh6",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh6.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/chilling-reign/chilling-reign-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh5|pack": {
      "name": "Booster Pack",
      "setId": "swsh5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/battle-styles/battle-styles-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh4.5|pack": {
      "name": "Booster Pack",
      "setId": "swsh4.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh4.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/shining-fates/shining-fates-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh4|pack": {
      "name": "Booster Pack",
      "setId": "swsh4",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh4.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/vivid-voltage/SWSH4_Booster_Zarude.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh3|pack": {
      "name": "Booster Pack",
      "setId": "swsh3",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh3.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/darkness-ablaze/darkness-ablaze-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh2|pack": {
      "name": "Booster Pack",
      "setId": "swsh2",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh2.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/rebel-clash/rebel-clash-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "swsh1|pack": {
      "name": "Booster Pack",
      "setId": "swsh1",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/swsh1.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/sword-and-shield/sword-and-shield-pack-0.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sm12|pack": {
      "name": "Booster Pack",
      "setId": "sm12",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sm12.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/cosmic-eclipse/SM12_Booster_Cleffa_Igglybuff_Togepi.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sm11.5|pack": {
      "name": "Booster Pack",
      "setId": "sm11.5",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sm11.5.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/hidden-fates/Hidden_Fates_Booster_Mew.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "sm9|pack": {
      "name": "Booster Pack",
      "setId": "sm9",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/sm9.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/team-up/SM9_Booster_Eevee_Snorlax.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "xy12|pack": {
      "name": "Booster Pack",
      "setId": "xy12",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/xy12.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/evolutions/XY12_Booster_Raichu.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    },
    "xy6|pack": {
      "name": "Booster Pack",
      "setId": "xy6",
      "productType": "BOOSTER PACKS",
      "packCount": 1,
      "imagePrimary": "assets/packs/xy6.webp",
      "imageAlternate": [],
      "sourceType": "existing-source-documented",
      "sourceUrl": "https://images.sealeddex.com/images/expansions/roaring-skies/XY6_Booster_Gallade.webp",
      "mirrorApproved": false,
      "reuse": "Existing repository asset; no new mirroring licence inferred"
    }
  }
}
;
