import {products,filterProducts,resolveSealedProductImage,fallback} from './model.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>Number.isFinite(n)?'$'+n.toFixed(2):'PRICE UNAVAILABLE';
export function installSealedVault(win=window,doc=document){
 const bridge=win.tcgCollectorBridge,tx=win.tcgCollector?.transactions,modal=doc.getElementById('sealedModalV161'),inspectModal=doc.getElementById('sealedInspectModalV179');
 if(!bridge||!tx||!modal||!inspectModal)return;
 let set='',type='',tab='shop',sort='value-high',favourite=false,min=0,quantity=0,page=0,shelfPage=0,inspected=null,confirmation=null;
 const rows=()=>products(win.tcgSealedLegacy?.catalog()||[],bridge.state());
 const product=id=>rows().find(p=>p.productId===id);
 const art=(p,q='thumb')=>`<div class="sealed-photo"><img src="${esc(resolveSealedProductImage(p.productId,q))}" alt="${esc(p.name)}" loading="lazy" decoding="async"><span class="sealed-image-status" ${p.custom?'':'hidden'}>IMAGE UNAVAILABLE</span></div>`;
 function images(root){root.querySelectorAll('.sealed-photo img').forEach(img=>{img.onerror=()=>{img.onerror=null;img.src=fallback;img.nextElementSibling.hidden=false;};});}
 function payload(action,p){return {...tx.review(),action,productId:p.productId,owned:p.ownedQuantity,displayed:p.displayed,unitCents:Math.round(p.marketValue*100)};}
 function commit(action,p,extra={}){try{tx.transact('sealed',{...payload(action,p),...extra});win.tcgSealedLegacy?.refresh();render();if(inspected)inspect(inspected);}catch(e){bridge.toast(e.message);}}
 function review(action,id){const p=product(id);if(!p)return;confirmation={...payload(action,p)};showDetail(p,action);}
 function closeInspect(){inspectModal.classList.remove('show');inspectModal.replaceChildren();inspected=null;confirmation=null;}
 function details(p){return `<p>${p.custom?'LEGACY CUSTOM PRODUCT · game contents preserved':'SOURCE-DOCUMENTED BOOSTER ART'}</p><button data-set-link="${esc(p.setId)}">${esc(p.setName)} · SET INFO</button><dl><dt>Product type</dt><dd>${esc(p.productType)}</dd><dt>${p.custom?'Game pack credits':'Packs'}</dt><dd>${p.packCount??'UNKNOWN'}</dd><dt>In-game market value</dt><dd>${money(p.marketValue)}</dd><dt>Owned / displayed</dt><dd>${p.ownedQuantity} / ${p.displayed}</dd>${p.acquired?`<dt>Latest acquisition</dt><dd>${new Date(p.acquired).toLocaleDateString()}</dd>`:''}</dl>${p.custom?'<p>No verified matching product image. This is a legacy game product, not official packaging.</p>':`<p>Single front view · no invented reverse side.</p><a href="${esc(p.sourceUrl)}" target="_blank" rel="noopener noreferrer">Artwork source</a>`}`;}
 function buttons(p){return `<div class="sealed-actions"><button data-act="buy" ${!p.unlocked||!Number.isFinite(p.marketValue)?'disabled':''}>BUY</button>${p.ownedQuantity?`<button data-act="display">${p.displayed?'REMOVE FROM SHELF':'ADD TO SHELF'}</button><button data-act="open" ${p.ownedQuantity<=p.displayed||!p.packCount?'disabled':''}>OPEN</button><button data-act="sell" ${p.ownedQuantity<=p.displayed||!Number.isFinite(p.marketValue)?'disabled':''}>SELL</button>`:''}<button data-act="favourite" aria-pressed="${p.favourite}">${p.favourite?'UNFAVOURITE':'FAVOURITE'}</button></div>`;}
 function showDetail(p,action=null){
  inspected=p.productId;inspectModal.className='sealedInspectModalV179 show sealed-viewer';inspectModal.setAttribute('role','dialog');inspectModal.setAttribute('aria-modal','true');inspectModal.setAttribute('aria-label',p.name);
  inspectModal.innerHTML=`<div class="sealed-detail"><button id="sealedInspectCloseV179" aria-label="Close product viewer">CLOSE</button><h2>${action?({open:'YOU ARE ABOUT TO OPEN',buy:'CONFIRM PURCHASE',sell:'CONFIRM SALE'}[action]):esc(p.name)}</h2>${action?`<h3>${esc(p.setName)} · ${esc(p.name)}</h3>`:''}<div class="sealed-studio">${art(p,'high')}</div>${!action?'<label class="sealed-zoom">Zoom <input type="range" min="1" max="2" step=".1" value="1" aria-label="Product zoom"></label>':''}${details(p)}${action?`<p>${action==='open'?`Receive exactly ${p.packCount} ${esc(p.setName)} pack credits. No cards are generated until you rip them.`:action==='sell'?`Receive ${money(Math.round(p.marketValue*.88*100)/100)} in game cash.`:`Pay ${money(p.marketValue)} in game cash.`}</p><div class="sealed-actions"><button id="sealedConfirm">${action.toUpperCase()}</button><button id="sealedCancel">CANCEL</button></div>`:buttons(p)}</div>`;
  images(inspectModal);inspectModal.querySelector('#sealedInspectCloseV179').onclick=closeInspect;
  inspectModal.querySelector('[data-set-link]').onclick=()=>{closeInspect();modal.classList.remove('show');win.tcgNavigation.go('collection','master');win.tcgCollector.collection.openSet(p.setId);};
  if(action){inspectModal.querySelector('#sealedCancel').onclick=()=>inspect(p.productId);let done=false;inspectModal.querySelector('#sealedConfirm').onclick=()=>{if(done)return;done=true;const button=inspectModal.querySelector('#sealedConfirm');button.disabled=true;try{tx.transact('sealed',confirmation);closeInspect();win.tcgSealedLegacy?.refresh();render();bridge.toast(action==='open'?'Pack credits added to the correct set.':'Sealed collection updated.');}catch(e){bridge.toast(e.message);closeInspect();render();}};}
  else {inspectModal.querySelectorAll('[data-act]').forEach(b=>b.onclick=()=>['buy','open','sell'].includes(b.dataset.act)?review(b.dataset.act,p.productId):commit(b.dataset.act,p));tilt(inspectModal.querySelector('.sealed-studio'),inspectModal.querySelector('input'));}
  inspectModal.querySelector('#sealedInspectCloseV179').focus();
 }
 function inspect(id){confirmation=null;const p=product(id);if(p)showDetail(p);}
 function tilt(stage,zoom){const image=stage.querySelector('.sealed-photo');let pointer=null,x=0,y=0;const reduced=win.matchMedia?.('(prefers-reduced-motion: reduce)').matches||doc.documentElement.classList.contains('v158ReducedMotion')||doc.documentElement.classList.contains('v158NoPackTilt');
  stage.onpointerdown=e=>{if(reduced||!e.isPrimary)return;pointer=e.pointerId;x=e.clientX;y=e.clientY;stage.setPointerCapture?.(pointer);};
  stage.onpointermove=e=>{if(pointer!==e.pointerId)return;image.style.transform=`perspective(900px) rotateY(${Math.max(-12,Math.min(12,(e.clientX-x)/12))}deg) rotateX(${Math.max(-8,Math.min(8,(y-e.clientY)/15))}deg) scale(${zoom.value})`;};
  const release=()=>{pointer=null;image.style.transform=`scale(${zoom.value})`;};stage.onpointerup=release;stage.onpointercancel=release;zoom.oninput=()=>{image.style.transform=`scale(${zoom.value})`;};
 }
 function render(){
  const all=rows(),owned=all.filter(p=>p.ownedQuantity),filtered=filterProducts(all,{set,type,owned:tab==='vault',sort,favourite,min,quantity}).filter(p=>tab==='vault'||p.unlocked),sets=bridge.sets();
  if(tab==='shop')filtered.sort((a,b)=>Number(a.custom)-Number(b.custom));
  page=Math.min(page,Math.max(0,Math.ceil(filtered.length/18)-1));const prefs=bridge.state().collectorV260?.sealed;
  const ordered=[...new Set([...(prefs?.order||[]),...Object.keys(bridge.state().sealedV161?.display||{})])];const displayed=ordered.map(id=>all.find(p=>p.productId===id)).filter(p=>p?.displayed&&p.ownedQuantity);
  shelfPage=Math.min(shelfPage,Math.max(0,Math.ceil(displayed.length/12)-1));
  modal.classList.add('sealed-vault');modal.setAttribute('role','dialog');modal.setAttribute('aria-label','Sealed collection');modal.setAttribute('aria-modal','true');
  modal.innerHTML=`<div class="sealed-room"><header><div><small>COLLECTOR ARCHIVE</small><h2>Sealed collection</h2></div><button id="sealedCloseV161">CLOSE</button></header><p>Authentic booster art. Unverified packaging is clearly marked as a legacy game product.</p><div class="sealed-stats"><span>OWNED <b>${owned.reduce((n,p)=>n+p.ownedQuantity,0)}</b></span><span>UNIQUE <b>${owned.length}</b></span><span>SEALED VALUE <b>${money(owned.reduce((n,p)=>n+(p.marketValue||0)*p.ownedQuantity,0))}</b></span><span>DISPLAYED <b>${displayed.reduce((n,p)=>n+p.displayed,0)}</b></span></div>
  <p>Most valuable owned: ${owned.length?esc([...owned].sort((a,b)=>(b.marketValue||0)-(a.marketValue||0))[0].name):'None yet'}${owned.some(p=>!Number.isFinite(p.marketValue))?' · Unpriced legacy items excluded from the value total.':''}</p><h3>Collector shelf</h3><div class="sealed-shelf">${displayed.length?displayed.slice(shelfPage*12,shelfPage*12+12).map(p=>`<article><button data-inspect="${esc(p.productId)}">${art(p)}<b>${esc(p.setName)}</b><span>${esc(p.name)} ×${p.displayed}</span></button><div class="sealed-actions"><button data-order="-1" data-key="${esc(p.productId)}" aria-label="Move left">←</button><button data-display="${esc(p.productId)}">REMOVE</button><button data-order="1" data-key="${esc(p.productId)}" aria-label="Move right">→</button></div></article>`).join(''):'<div class="sealed-empty"><h4>YOUR DISPLAY SHELF IS EMPTY</h4><p>Showcase favourites from your sealed vault here.</p><button id="sealedViewVault">VIEW SEALED INVENTORY</button></div>'}</div>${displayed.length>12?'<div class="sealed-actions"><button data-shelf-page="-1">PREVIOUS SHELF</button><button data-shelf-page="1">NEXT SHELF</button></div>':''}
  <div class="sealed-actions"><button data-tab="shop" aria-pressed="${tab==='shop'}">PRODUCTS</button><button data-tab="vault" aria-pressed="${tab==='vault'}">SEALED VAULT</button></div><div class="sealed-filters"><label>Set<select id="sealedSet"><option value="">All sets</option>${sets.map(s=>`<option value="${esc(s.id)}" ${set===s.id?'selected':''}>${esc(s.name)}</option>`).join('')}</select></label><label>Type<select id="sealedType"><option value="">ALL PRODUCTS</option>${[...new Set(all.map(p=>p.productType))].map(t=>`<option ${type===t?'selected':''}>${t}</option>`).join('')}</select></label><details class="sealed-extra"><summary>VALUE, QUANTITY & SORT</summary><div class="sealed-extra-fields"><label>Sort<select id="sealedSort">${['value-high','value-low','set','type','newest','quantity'].map(t=>`<option value="${t}" ${sort===t?'selected':''}>${t.replace('-',' ').toUpperCase()}</option>`).join('')}</select></label><label>Minimum value<input id="sealedMin" type="number" min="0" value="${min}"></label><label>Minimum quantity<input id="sealedQty" type="number" min="0" value="${quantity}"></label></div></details><button id="sealedFavourites" aria-pressed="${favourite}">FAVOURITES</button></div>
  <div class="sealed-grid">${filtered.slice(page*18,page*18+18).map(p=>`<article class="sealed-tile">${art(p)}<small>${p.custom?'LEGACY CUSTOM PRODUCT':'BOOSTER PACK'}</small><h3>${esc(p.name)}</h3><button data-set="${esc(p.setId)}">${esc(p.setName)}</button><p>${p.packCount??'?'} ${p.custom?'game pack credits':'pack'} · Owned ×${p.ownedQuantity}</p><b>${money(p.marketValue)}</b><small>IN-GAME VALUE</small><div class="sealed-actions"><button data-inspect="${esc(p.productId)}">INSPECT</button><button data-buy="${esc(p.productId)}" ${!p.unlocked||!Number.isFinite(p.marketValue)?'disabled':''}>BUY</button>${p.ownedQuantity?`<button data-display="${esc(p.productId)}">${p.displayed?'REMOVE FROM SHELF':'ADD TO SHELF'}</button>`:''}</div></article>`).join('')||'<p>No products match these filters.</p>'}</div><div class="sealed-actions"><button data-page="-1" ${!page?'disabled':''}>PREVIOUS</button><span>${page+1} / ${Math.max(1,Math.ceil(filtered.length/18))}</span><button data-page="1" ${(page+1)*18>=filtered.length?'disabled':''}>NEXT</button></div></div>`;
  images(modal);modal.querySelector('#sealedCloseV161').onclick=()=>modal.classList.remove('show');
  modal.querySelectorAll('[data-inspect]').forEach(b=>b.onclick=()=>inspect(b.dataset.inspect));modal.querySelectorAll('[data-buy]').forEach(b=>b.onclick=()=>review('buy',b.dataset.buy));modal.querySelectorAll('[data-display]').forEach(b=>b.onclick=()=>commit('display',product(b.dataset.display)));modal.querySelectorAll('[data-order]').forEach(b=>b.onclick=()=>commit('reorder',product(b.dataset.key),{direction:Number(b.dataset.order)}));
  modal.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;page=0;render();});modal.querySelector('#sealedViewVault')?.addEventListener('click',()=>{tab='vault';set='';page=0;render();});
  for(const [id,assign] of [['sealedSet',v=>set=v],['sealedType',v=>type=v],['sealedSort',v=>sort=v],['sealedMin',v=>min=Math.max(0,Number(v)||0)],['sealedQty',v=>quantity=Math.max(0,Number(v)||0)]])modal.querySelector('#'+id).onchange=e=>{assign(e.target.value);page=0;render();};
  modal.querySelector('#sealedFavourites').onclick=()=>{favourite=!favourite;page=0;render();};modal.querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>{page+=Number(b.dataset.page);render();});modal.querySelectorAll('[data-shelf-page]').forEach(b=>b.onclick=()=>{shelfPage=Math.max(0,shelfPage+Number(b.dataset.shelfPage));render();});
  modal.querySelectorAll('[data-set]').forEach(b=>b.onclick=()=>{modal.classList.remove('show');win.tcgNavigation.go('collection','master');win.tcgCollector.collection.openSet(b.dataset.set);});
 }
 let account=bridge.account();const refreshAccount=()=>{if(account!==bridge.account()){account=bridge.account();set='';page=0;shelfPage=0;closeInspect();if(modal.classList.contains('show'))render();}};for(const event of ['tcg:profile-updated','tcg:hub-updated','tcg:collector-updated'])win.addEventListener(event,refreshAccount);
 doc.addEventListener('keydown',e=>{if(e.key==='Escape'){closeInspect();modal.classList.remove('show');}});
 return win.tcgSealed={render,inspect,review,display:id=>{const p=product(id);if(p)commit('display',p);},open(id){set=rows().some(p=>p.setId===id)?id:'';page=0;render();modal.classList.add('show');}};
}
