import test from 'node:test';
import assert from 'node:assert/strict';
import {parseHTML} from 'linkedom';
import {readFileSync} from 'node:fs';
import {installCollectorNavigation,DESTINATIONS,COLLECTION_TABS} from '../src/app/collector-navigation.js';
function fixture(){const {document,window}=parseHTML('<html><body>'+readFileSync('public/ui/chrome.html','utf8')+['rip','binder','bulk','earn','profile'].map(id=>`<section class="screen" id="${id}">${id==='binder'?['binder','grading','vault'].map(x=>`<div data-binder-panel="${x}"></div>`).join(''):''}</section>`).join('')+'</body></html>');delete window.tcgNavigation;window.scrollTo=()=>{};return{document,window};}
test('four primary destinations route once and Collection owns Bulk',()=>{const {document,window}=fixture();const router=installCollectorNavigation(window,document);assert.equal(document.querySelectorAll('.nav button').length,4);for(const target of DESTINATIONS){router.go(target);assert.equal(document.querySelectorAll('.screen.active').length,1);assert.equal(document.querySelectorAll('.nav .active').length,1);assert.equal(router.snapshot().destination,target);}router.go('bulk');assert.equal(router.snapshot().destination,'collection');assert.equal(document.querySelector('.screen.active').id,'bulk');assert.equal(document.querySelector('.nav .active').dataset.destination,'collection');});
test('Collection tabs preserve existing grading and slab panels and reject unknown routes',()=>{const{document,window}=fixture();const router=installCollectorNavigation(window,document);for(const tab of COLLECTION_TABS){router.go('collection',tab);assert.equal(document.querySelector('[data-collection-tab].active').dataset.collectionTab,tab);}router.go('collection','grading');assert.ok(document.querySelector('[data-binder-panel="grading"]').classList.contains('active'));assert.equal(router.go('garbage'),false);assert.equal(router.snapshot().destination,'collection');});
test('navigation safe-area and loader rules are centralized',()=>{const css=readFileSync('public/styles/collector-v260.css','utf8');assert.match(css,/safe-area-inset-bottom/);assert.match(css,/grid-template-columns:repeat\(4/);assert.match(css,/modern-booting \.nav/);});
