import test from 'node:test';
import assert from 'node:assert/strict';
import {migrateCollector,cardRows,collectionValue,filterCards,population,gradeEstimate} from '../src/collector/model.js';
import {createTransactions} from '../src/collector/transactions.js';
import {refreshContracts,contractDay} from '../src/collector/contracts.js';
function fixture(){let state={coins:100,xp:300,packs:10,binder:{hit:{id:'hit',name:'Hit',qty:2,market:10}},bulkV64:{common:{id:'common',name:'Common',qty:50,market:.1,setId:'set'}},shopV84:{rep:10},jobs:{sort:8},unknownFutureField:{keep:true}};migrateCollector(state,1000);let account='one',blocked=false;const bridge={state:()=>state,save(){},commit:n=>state=n,account:()=>account,blocked:()=>blocked,price:c=>c.market,totals:()=>({set:{name:'Set',total:4,owned:new Set(['a','b','c','d'])}})};const service=createTransactions(bridge,{now:()=>1000,id:()=>Math.random().toString()});return{bridge,service,state:()=>state,account:x=>account=x,block:x=>blocked=x};}
test('additive migration preserves every asset, old rep/jobs and unknown save fields; reload grants once',()=>{const f=fixture(),s=f.state();assert.equal(s.xp,500);assert.deepEqual(s.jobs,{sort:8});assert.equal(s.shopV84.rep,10);assert.equal(s.binder.hit.qty,2);assert.equal(s.collectorV260.legacy.cardShowUnlocked,true);assert.equal(s.badges.legacy_dealer,true);assert.equal(migrateCollector(s,2000),false);assert.equal(s.xp,500);assert.deepEqual(s.unknownFutureField,{keep:true});});
test('reviewed sale applies once, rejects stale quantity, changed price, locks and account changes',()=>{const f=fixture(),svc=f.service,plan={...svc.review(),cardId:'hit',source:'binder',qty:1,owned:2,unitCents:1000};svc.transact('sell',plan,'sale');svc.transact('sell',plan,'sale');assert.equal(f.state().coins,110);assert.equal(f.state().binder.hit.qty,1);assert.throws(()=>svc.transact('sell',plan,'other'),/changed/);const next={...svc.review(),...plan,revision:f.state().collectorV260.revision,owned:1};f.state().binder.hit.market=20;assert.throws(()=>svc.transact('sell',next),/price changed/);f.account('two');assert.throws(()=>svc.transact('sell',next),/account changed/);f.account('one');f.state().collectorV260.cards.hit={locked:true};assert.throws(()=>svc.transact('sell',next),/Unlock/);});
test('transactions reject negative quantities, insufficient copies and cloud recovery',()=>{const f=fixture(),p={...f.service.review(),cardId:'hit',source:'binder',owned:2,unitCents:1000};for(const qty of [-1,0,3,1.5])assert.throws(()=>f.service.transact('sell',{...p,qty}));assert.equal(f.state().coins,100);f.block(true);assert.throws(()=>f.service.transact('sell',{...p,qty:1}),/sync/);});
test('routing conserves copies and cash; chases enforce maximum and persist',()=>{const f=fixture();f.service.transact('move',{...f.service.review(),cardId:'hit',source:'binder',qty:1,owned:2});assert.equal(f.state().binder.hit.qty+f.state().bulkV64.hit.qty,2);assert.equal(f.state().coins,100);for(let i=0;i<3;i++)f.service.transact('chase',{...f.service.review(),card:{id:''+i,name:'Card '+i}});assert.throws(()=>f.service.transact('chase',{...f.service.review(),card:{id:'four',name:'Four'}}),/three/);assert.equal(JSON.parse(JSON.stringify(f.state())).collectorV260.chases.length,3);});
test('contracts keep one, freeze offers, pay atomically, expire and cannot be claimed twice',()=>{const f=fixture(),s=f.state();const offers=refreshContracts(s,0),offer=offers[0];assert.ok(offer.lines.every(l=>l.qty<s.bulkV64[l.id].qty));const p={...f.service.review(),contractId:offer.id};f.service.transact('contract',p,'delivery');const cash=f.state().coins;f.service.transact('contract',p,'delivery');assert.equal(f.state().coins,cash);assert.throws(()=>f.service.transact('contract',{...f.service.review(),contractId:offer.id}),/completed/);assert.equal(f.state().bulkV64.common.qty,10);refreshContracts(f.state(),1);assert.equal(f.state().collectorV260.contracts[offer.id],undefined);f.state().collectorV260.lastDay=5;assert.equal(contractDay(f.state(),0),5);});
test('Master milestones require completion and have durable claim markers',()=>{const f=fixture();f.service.transact('master',{...f.service.review(),setId:'set',milestone:25});assert.equal(f.state().coins,125);assert.throws(()=>f.service.transact('master',{...f.service.review(),setId:'set',milestone:25}),/already/);assert.throws(()=>f.service.transact('master',{...f.service.review(),setId:'unknown',milestone:100}),/Complete/);});
test('owned inventory and value include grading/listings/escrow without double counting',()=>{const s={binder:{a:{id:'a',qty:2,market:10}},bulkV64:{a:{id:'a',qty:3,market:10}},gradingV44:{submissions:[{id:'a',raw:10}],graded:[{id:'a',grade:10,raw:10}]},marketV57:{listings:[{id:'a',market:10}]},hubEscrowV256:[{id:'a',market:10}]};const row=cardRows(s)[0];assert.equal(row.qty,9);assert.equal(collectionValue(s,c=>c.market||c.raw,c=>c.raw*4).total,120);assert.equal(population(s,'a').ten,1);assert.equal(filterCards([row],{query:'a',filter:'duplicates'}).length,1);assert.ok(gradeEstimate({centering:95,edges:87,corners:90,surface:92}).low<gradeEstimate({centering:95,edges:87,corners:90,surface:92}).high);});
test('grading charges exactly once, preserves condition and varies time rather than outcome by service',()=>{for(const tier of ['standard','priority','express']){const f=fixture();f.state().binder.hit.conditionV161={centering:96,corners:94,edges:93,surface:97};const condition=structuredClone(f.state().binder.hit.conditionV161);const p={...f.service.review(),cardId:'hit',source:'binder',owned:2,tier};f.service.transact('grade',p,'grade');f.service.transact('grade',p,'grade');const s=f.state();assert.equal(s.gradingV44.submissions.length,1);assert.deepEqual(s.gradingV44.submissions[0].condition,condition);assert.equal(s.binder.hit.qty,1);assert.equal(s.coins,100-({standard:12,priority:25,express:45})[tier]);assert.equal(s.gradingV44.submissions[0].dueOpen,({standard:5,priority:3,express:1})[tier]);assert.equal(s.gradingV44.submissions[0].collectorV260,true);}});
test('multi-card bulk sales validate the whole delivery before mutating any inventory',()=>{const f=fixture();f.state().bulkV64.second={id:'second',qty:2,market:1};const p={...f.service.review(),keepOne:true,total:300,lines:[{id:'common',qty:20,owned:50,unitCents:10},{id:'second',qty:1,owned:3,unitCents:100}]};assert.throws(()=>f.service.transact('bulkSale',p),/changed/);assert.equal(f.state().bulkV64.common.qty,50);assert.equal(f.state().coins,100);p.lines[1].owned=2;f.service.transact('bulkSale',p);assert.equal(f.state().coins,103);assert.equal(f.state().bulkV64.second.qty,1);});
test('sealed shelf value is included exactly once in total collection value',()=>{const value=collectionValue({binder:{a:{id:'a',qty:1,market:10}}},c=>c.market,()=>0,50);assert.deepEqual(value,{raw:10,graded:0,sealed:50,total:60});});

test('NPC swaps conserve copies, honor locks, and retain a durable acceptance receipt',()=>{const f=fixture(),p={...f.service.review(),cardId:'hit',owned:2,offerId:'day:hit:received',take:{id:'received',name:'Received',setId:'set',market:10}};f.service.transact('npcTrade',p,'npc');assert.equal(f.state().binder.hit.qty,1);assert.equal(f.state().binder.received.qty,1);assert.equal(f.state().coins,100);assert.equal(f.state().tradeV154.count,1);assert.throws(()=>f.service.transact('npcTrade',{...p,...f.service.review(),owned:1}),/already/);assert.equal(f.state().binder.hit.qty,1);});

test('live server clock resists wall-clock changes and discards cross-account samples',async()=>{const {createCollectorClock}=await import('../src/collector/clock.js');let user='a',wall=1000,tick=20;const clock=createCollectorClock({account:()=>user,wall:()=>wall,monotonic:()=>tick});assert.equal(clock.source(),'local');assert.equal(clock.accept('2026-10-07T12:00:00Z','a'),true);const first=clock.now();wall+=86400000;tick+=1000;assert.equal(clock.now(),first+1000);assert.equal(clock.accept('2026-10-06T12:00:00Z','a'),false);user='b';assert.equal(clock.source(),'local');assert.equal(clock.now(),wall);assert.equal(clock.accept('2026-10-07T12:00:00Z','a'),false);});
test('Master Set+ is separate from normal completion and cosmetic claims cannot repeat',()=>{const f=fixture();assert.throws(()=>f.service.transact('masterPlus',{...f.service.review(),setId:'set',tier:'elite'}),/grading collection/);f.state().gradingV44={graded:['a','b','c','d'].map(id=>({id,setId:'set',grade:8}))};f.service.transact('masterPlus',{...f.service.review(),setId:'set',tier:'elite'});assert.equal(f.state().coins,100);assert.equal(f.state().badges.masterplus_set_elite,true);assert.throws(()=>f.service.transact('masterPlus',{...f.service.review(),setId:'set',tier:'elite'}),/already/);assert.throws(()=>f.service.transact('masterPlus',{...f.service.review(),setId:'set',tier:'perfect'}),/grading collection/);});

test('District offers freeze within the game day and purchases consume them atomically once',async()=>{const {districtOffer}=await import('../src/collector/district.js');const f=fixture();let calls=0;const generate=()=>{calls++;return {title:'Dealer',cards:[{id:'new',name:'New',market:3}],minCents:200,maxCents:300};};const first=districtOffer(f.state(),0,'dealer',generate);assert.deepEqual(districtOffer(f.state(),0,'dealer',generate),first);assert.equal(calls,1);const plan={...f.service.review(),key:'dealer',day:0,costCents:250};f.service.transact('districtPurchase',plan,'purchase');assert.equal(f.state().coins,97.5);assert.equal(f.state().binder.new.qty,1);assert.equal(districtOffer(f.state(),0,'dealer',generate),null);assert.throws(()=>f.service.transact('districtPurchase',{...plan,...f.service.review()}),/no longer/);assert.ok(districtOffer(f.state(),1,'dealer',generate));assert.equal(calls,2);assert.equal(f.state().shopV84.rep,10);});
test('District price or expiry rejection changes neither cash nor inventory',async()=>{const {districtOffer}=await import('../src/collector/district.js');const f=fixture();districtOffer(f.state(),0,'dealer',()=>({cards:[{id:'new',name:'New'}],minCents:100,maxCents:300}));for(const price of [-100,0,99,301])assert.throws(()=>f.service.transact('districtPurchase',{...f.service.review(),key:'dealer',day:0,costCents:price}),/price/);f.state().collectorV260.lastDay=1;assert.throws(()=>f.service.transact('districtPurchase',{...f.service.review(),key:'dealer',day:0,costCents:200}),/no longer/);assert.equal(f.state().coins,100);assert.equal(f.state().binder.new,undefined);});

test('earned Master and legacy cosmetics appear without leaking entitlement across accounts',async()=>{const vm=await import('node:vm'),fs=await import('node:fs');const context=vm.createContext({window:{},state:{badges:{legacy_dealer:true},collectorV260:{masterRewards:{'set:75':true},masterPlus:{'set:elite':true}}},SETS:[{id:'set',name:'Set',a:'#aaa',b:'#bbb'}],BINDER_THEMES:[],BADGE_DEFS:[]});vm.runInContext(fs.readFileSync('public/runtime/collector-bridge.js','utf8'),context);context.window.tcgCollectorBridge.syncCosmetics();assert.equal(context.BINDER_THEMES[0].id,'master-set');assert.equal(context.state.binderOwned.includes('master-set'),true);assert.equal(context.BADGE_DEFS.length,3);context.state={badges:{},collectorV260:{}};context.window.tcgCollectorBridge.syncCosmetics();assert.equal(context.state.binderOwned,undefined);assert.ok(context.BADGE_DEFS.every(b=>!b[3]()));});

test('transaction receipts support LAN browsers without randomUUID using secure random bytes',async()=>{const {transactionId}=await import('../src/utils/transaction-id.js');let n=0;const crypto={getRandomValues(bytes){for(let i=0;i<bytes.length;i++)bytes[i]=n++;return bytes;}};const a=transactionId(crypto),b=transactionId(crypto);assert.match(a,/^[a-f0-9]{8}-[a-f0-9]{4}-4[a-f0-9]{3}-[89ab][a-f0-9]{3}-[a-f0-9]{12}$/);assert.notEqual(a,b);assert.equal(transactionId({randomUUID:()=>a}),a);assert.throws(()=>transactionId({}),/receipt/);});
