import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import {randomUUID} from 'node:crypto';
import {database,USERS} from './hub-database.mjs';import {battleStats,validateDraft} from '../src/league/rules.js';
async function setup(){const h=await database();for(const f of ['20261008010000_battle_live_sync.sql','20261008020000_hub_snapshot_timeout.sql','20261008040000_collector_league.sql'])await h.db.exec(await readFile(new URL('../supabase/migrations/'+f,import.meta.url),'utf8'));
 const call=(u,action,payload={},id=randomUUID())=>h.db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[u||'']);await tx.exec('set local role authenticated');return(await tx.query('select public.league_command($1,$2,$3) as result',[action,JSON.stringify(payload),id])).rows[0].result;});return {...h,league:call};}
const A=USERS[0],B=USERS[1];
async function matched(h){await h.league(A,'queue_join');let b=await h.league(B,'queue_join');if(b.queue){await h.db.exec("update hub_private.league_queue set joined_at=now()-interval '80 seconds'");b=await h.league(B,'queue_tick');}assert.equal(b.match.phase,'clash');const m=b.match;await h.league(A,'ready',{match_id:m.id,revision:m.revision});return h.league(B,'ready',{match_id:m.id,revision:m.revision});}
const cheapest=cards=>cards.map((c,i)=>({i,cost:battleStats(c).cost})).sort((a,b)=>a.cost-b.cost).slice(0,5).map(x=>x.i);
async function draft(h,state){const id=state.match.id;await h.league(A,'reveal',{match_id:id,progress:10});await h.league(B,'reveal',{match_id:id,progress:10});for(const u of [A,B]){const s=await h.league(u,'snapshot');await h.league(u,'draft_confirm',{match_id:id,revision:s.match.revision,indices:cheapest(s.match.cards)});}return h.league(A,'snapshot');}
test('Draft Duel is default-off, authenticated, private and migration can be reapplied',async()=>{const h=await setup();try{assert.equal((await h.league(A,'snapshot')).enabled,false);await assert.rejects(h.league(null,'snapshot'),/AUTH_REQUIRED/);await assert.rejects(h.league(A,'queue_join'),/DISABLED/);await h.db.exec(await readFile(new URL('../supabase/migrations/20261008040000_collector_league.sql',import.meta.url),'utf8'));await assert.rejects(h.db.exec('set role authenticated;select * from hub_private.league_matches'),/permission/);}finally{await h.close();}});
test('server and UI derive identical deterministic stats from card identity and optional metadata',async()=>{const h=await setup();try{for(let i=0;i<40;i++){const c={id:'card-'+i,tier:i%6,rarity:i%3?'Rare':'Uncommon',hp:120,types:['fire']};assert.deepEqual((await h.db.query('select hub_private.league_stats($1) as v',[c])).rows[0].v,battleStats(c));}}finally{await h.close();}});
test('10 LOCAL role-authenticated simulations preserve awards and settle once; not live QA certification',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[ [A,B] ]);
 const totals=async u=>(await h.db.query("select save_data#>'{state}' as s from public.user_saves where user_id=$1",[u])).rows[0].s;
 for(let game=0;game<10;game++){
  let s=await matched(h);const id=s.match.id;assert.equal(s.match.cards.length,10);assert.equal(s.match.opponent_cards.length,0);const b0=await totals(B);
  await h.league(A,'reveal',{match_id:id,progress:3});let v=await h.league(B,'snapshot');assert.equal(v.match.opponent_cards.length,3);await h.league(A,'reveal',{match_id:id,progress:1});assert.equal((await h.league(B,'snapshot')).match.opponent_cards.length,3);
  await assert.rejects(h.league(USERS[2],'reveal',{match_id:id,progress:10}),/DISABLED/);
  s=await draft(h,s);
  for(let t=0;t<20&&s.match.phase==='battle';t++){
   const rev=s.match.revision,turn=s.match.turn,p={match_id:id,revision:rev,turn,action:{kind:'attack'}},receipt=randomUUID();
   await h.league(A,'turn_submit',p,receipt);v=await h.league(B,'snapshot');assert.equal(v.match.opponent_locked,true);assert.equal(v.match.action_a,undefined);assert.equal(v.match.last_turn?.a?.kind,t?'attack':undefined);
   await h.league(A,'turn_submit',p,receipt);await assert.rejects(h.league(A,'turn_submit',p),/ACTION_LOCKED/);
   s=await h.league(B,'turn_submit',p);assert.ok(s.match.turn>turn||s.match.phase==='result');
   await assert.rejects(h.league(A,'turn_submit',p),/STALE_REVISION|PHASE_CHANGED/);
   assert.ok(JSON.stringify(s).length<18000);
  }
  assert.equal(s.match.phase,'result');const result=s.match.result;assert.equal(Object.keys(result).filter(k=>[A,B].includes(k)).length,2);
  for(const u of [A,B]){assert.equal(result[u].after,result[u].before+result[u].delta);assert.ok(result[u].delta>=-24&&result[u].delta<=28);}
  const before=JSON.stringify(result);await h.league(A,'cancel',{match_id:id});assert.equal(JSON.stringify((await h.league(B,'snapshot')).match.result),before);assert.deepEqual(await totals(B),b0);
 }
 for(const u of [A,B]){const s=await totals(u);assert.equal(s.packs,10);assert.equal(s.starterV199.remaining,0);const copies=Object.values(s.binder).concat(Object.values(s.bulkV64)).reduce((n,c)=>n+c.qty,0);assert.equal(copies,103);assert.equal(s.coins,100);}
}finally{await h.close();}});
test('draft, turn and cosmetic validators reject cheats; expired turns default safely',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[[A,B]]);let s=await matched(h);const id=s.match.id;await h.league(A,'reveal',{match_id:id,progress:10});s=await h.league(B,'reveal',{match_id:id,progress:10});await assert.rejects(h.league(A,'draft_confirm',{match_id:id,revision:s.match.revision,indices:[0,0,1,2,3]}),/DUPLICATE/);await assert.rejects(h.league(A,'draft_confirm',{match_id:id,revision:s.match.revision,indices:[0,1,2,3,99]}));
 s=await draft(h,{match:{id}}).catch(async()=>{for(const u of [A,B]){const x=await h.league(u,'snapshot');await h.league(u,'draft_confirm',{match_id:id,revision:x.match.revision,indices:cheapest(x.match.cards)});}return h.league(A,'snapshot');});
 await assert.rejects(h.league(A,'turn_submit',{match_id:id,revision:s.match.revision,turn:s.match.turn,action:{kind:'swap',target:0}}),/INVALID_SWAP/);
 await assert.rejects(h.league(A,'banner',{theme:'smoky-legendary',frame:'apex',trackers:[]}),/NOT_EARNED/);
 await h.db.query("update hub_private.league_matches set deadline=now()-interval '1 second' where id=$1",[id]);s=await h.league(A,'tick',{match_id:id});assert.equal(s.match.turn,2);assert.equal(s.match.last_turn.a.kind,'defend');assert.equal(s.match.last_turn.b.kind,'defend');assert.equal(s.match.action_locked,false);
}finally{await h.close();}});
test('private signals, permanent rank cosmetics and large-history snapshots stay bounded',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[[A,B]]);let s=await matched(h);const id=s.match.id;s=await draft(h,s);const before=await h.league(A,'snapshot');
 const large=Object.fromEntries(Array.from({length:10000},(_,i)=>['large-'+i,{id:'large-'+i,name:'Collection card '+i,qty:50,market:1}]));await h.db.query("update public.user_saves set save_data=jsonb_set(save_data,'{state,binder}',$2) where user_id=$1",[A,large]);
 await h.db.query("insert into hub_private.league_matches(host_id,guest_id,phase,rules,created_at,finished_at) select $1,$2,'result','{}',now()-interval '1 day'-n*interval '1 second',now()-interval '1 day' from generate_series(1,2000) n",[A,B]);await h.db.exec('analyze hub_private.league_matches');
 const timings=[];for(let i=0;i<20;i++){const at=performance.now();s=await h.league(A,'snapshot');timings.push(performance.now()-at);}assert.equal(s.match.id,id);assert.equal(s.match.revision,before.match.revision);assert.ok(JSON.stringify(s).length<18000);assert.ok(!JSON.stringify(s).includes('large-9999'));console.log('LOCAL League large collection/history snapshot ms median/max',timings.sort((a,b)=>a-b)[10],Math.max(...timings),'bytes',JSON.stringify(s).length);
 const plan=(await h.db.query('explain (analyze,format json) select id from hub_private.league_matches where host_id=$1 order by created_at desc limit 1',[A])).rows[0]['QUERY PLAN'];assert.match(JSON.stringify(plan),/league_host_history/);
 await h.db.query('update hub_private.profiles set rp=1000,season_high=1000 where user_id=$1',[A]);await h.league(A,'banner',{theme:'smoky-legendary',frame:'diamond',trackers:['draft_wins','draft_matches','rp']});await h.db.query('update hub_private.profiles set rp=0,show_record=false where user_id=$1',[A]);s=await h.league(B,'snapshot');const p=s.match.host_id===A?s.match.host_profile:s.match.guest_profile;assert.deepEqual(p.league_stats,{});assert.equal(p.highest,null);assert.equal(p.banner.frame,'diamond');await h.league(A,'banner',{theme:'smoky-legendary',frame:'diamond',trackers:['rp']});
 await h.db.transaction(async tx=>{await tx.query("select set_config('request.jwt.claim.sub',$1,true)",[A]);await tx.exec('set local role authenticated');const rows=(await tx.query('select * from public.league_signals')).rows;assert.equal(rows.length,1);assert.equal(rows[0].user_id,A);});
}finally{await h.close();}});
test('God Pack budget is legal without changing pulls, and tier advantage is deliberately capped',async()=>{const h=await setup();try{const cards=Array.from({length:10},(_,i)=>({id:'god-'+i,tier:5}));const d=(await h.db.query('select hub_private.league_auto_draft($1) as d',[cards])).rows[0].d;assert.equal(d.cost,150);assert.equal(d.squad.length,5);for(let i=0;i<10;i++){const low=battleStats({...cards[i],tier:0}),high=battleStats(cards[i]);assert.equal(high.power-low.power,3);assert.equal(high.max_hp,low.max_hp);}}finally{await h.close();}});
test('all tactical actions resolve atomically, defend blocks damage, swaps change target and heals restore HP',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[[A,B]]);let s=await matched(h);s=await draft(h,s);const id=s.match.id;const cards=Array.from({length:100},(_,i)=>({id:'tactic-'+i,tier:0}));const healer=cards.find(c=>battleStats(c).ability==='heal');const squad=[healer,...cards.filter(c=>c!==healer).slice(0,4)];let base=(await h.db.query("select hub_private.league_draft($1,'[0,1,2,3,4]') as d",[squad])).rows[0].d;
 const resolve=async(a,b,own=base)=>{await h.db.query("update hub_private.league_matches set phase='battle',turn=1,revision=10,combat=$2,action_a=$3,action_b=$4,deadline=now()+interval '12 seconds' where id=$1",[id,{a:own,b:base},a,b]);await h.db.query('select hub_private.league_resolve($1)',[id]);return (await h.league(A,'snapshot')).match;};
 let result=await resolve({kind:'attack'},{kind:'defend'});assert.ok(result.combat.b.metrics.blocked>0);assert.ok(result.combat.a.metrics.damage>0);assert.equal(result.combat.b.metrics.damage,0);
 result=await resolve({kind:'swap',target:3},{kind:'attack'});assert.equal(result.combat.a.active,3);assert.equal(result.combat.a.squad[0].hp,base.squad[0].hp);assert.ok(result.combat.a.squad[3].hp<base.squad[3].hp);assert.equal(result.combat.a.metrics.swaps,1);
 const wounded=structuredClone(base);wounded.squad[0].hp-=30;result=await resolve({kind:'ability'},{kind:'defend'},wounded);assert.equal(result.combat.a.squad[0].hp,wounded.squad[0].hp+24);assert.equal(result.combat.a.squad[0].uses,1);assert.equal(result.combat.a.squad[0].cooldown,2);assert.equal(result.combat.a.metrics.ability,24);
 await assert.rejects(h.league(A,'turn_submit',{match_id:id,revision:result.revision,turn:result.turn,action:{kind:'ability'}}),/ABILITY_UNAVAILABLE/);
}finally{await h.close();}});
test('balance simulation: common type counters remain viable against max-rarity squads',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[[A,B]]);const start=await matched(h),id=start.match.id;let wins=0,turns=0;for(let seed=0;seed<40;seed++){
 const low=Array.from({length:5},(_,i)=>({id:`balance-${seed}-${i}`,tier:0,types:['fire']}));const high=low.map(c=>({...c,tier:5,types:['grass']}));const x=(await h.db.query("select hub_private.league_draft($1,'[0,1,2,3,4]') a,hub_private.league_draft($2,'[0,1,2,3,4]') b",[low,high])).rows[0];await h.db.query("update hub_private.league_matches set phase='battle',turn=1,combat=$2,result=null where id=$1",[id,x]);
 let m;do{await h.db.query("update hub_private.league_matches set action_a='{\"kind\":\"attack\"}',action_b='{\"kind\":\"attack\"}',deadline=now()+interval '12 seconds' where id=$1",[id]);await h.db.query('select hub_private.league_resolve($1)',[id]);m=(await h.db.query('select phase,turn,result from hub_private.league_matches where id=$1',[id])).rows[0];}while(m.phase==='battle');if(m.result.winner===start.match.host_id)wins++;turns+=m.turn-1;
 }console.log('LOCAL balance counterfactual: common fire vs max-rarity grass wins',wins,'/40; average turns',turns/40);assert.ok(wins>=30,'type decisions must overcome three-point rarity ceiling');
}finally{await h.close();}});
test('RP search begins narrow, widens with queue age and cancellation removes queue',async()=>{const h=await setup();try{await h.db.query('update hub_private.league_config set qa_users=$1',[[A,B]]);for(const u of [A,B]){await h.league(u,'queue_join');await h.league(u,'queue_cancel');}await h.db.query('update hub_private.profiles set rp=400 where user_id=$1',[B]);await h.league(A,'queue_join');let s=await h.league(B,'queue_join');assert.ok(s.queue);assert.ok(!s.match);await h.db.exec("update hub_private.league_queue set joined_at=now()-interval '31 seconds'");s=await h.league(A,'queue_tick');assert.equal(s.match.phase,'clash');await h.league(A,'cancel',{match_id:s.match.id});await h.league(A,'queue_join');s=await h.league(A,'queue_cancel');assert.equal(s.queue,null);}finally{await h.close();}});
