import test from 'node:test';import assert from 'node:assert/strict';import {LeagueController,phaseOf} from '../src/league/controller.js';import {battleStats,squadBudget,validateDraft,ratingDelta} from '../src/league/rules.js';import {competitiveBanner} from '../src/league/banner.js';
const deferred=()=>{let resolve;return {p:new Promise(r=>resolve=r),resolve};};
const data=(phase='opening',extra={})=>({version:262,enabled:true,user_id:'qa',server_time:new Date().toISOString(),profile:{rp:100},save_version:1,match:{id:'match',phase,revision:1,turn:1,my_progress:0,...extra}});
function harness(rpc){const map=new Map(),events=[];const c=new LeagueController({client:{rpc,removeChannel:()=>{}},storage:{setItem:(k,v)=>map.set(k,v),getItem:k=>map.get(k),removeItem:k=>map.delete(k)},bridge:{begin:async()=>events.push('begin'),finish:async()=>events.push('finish'),hold:()=>events.push('hold'),sync:async()=>events.push('sync')},uuid:()=>crypto.randomUUID()});c.uid='qa';c.state.data=data();return {c,events,map};}
test('phase model distinguishes queue, ready, action locked and result',()=>{assert.equal(phaseOf({queue:{}}),'QUEUED');assert.equal(phaseOf(data('draft',{my_draft:[0,1,2,3,4]})),'READY');assert.equal(phaseOf(data('battle',{action_locked:true})),'RESOLVING');assert.equal(phaseOf(data('result')),'RESULT');});
test('rapid reveals coalesce while preserving monotonic progress',async()=>{const d=deferred(),calls=[];const {c}=harness(async(_,{p_action,p_payload})=>{calls.push(p_payload.progress);if(calls.length===1)await d.p;return {data:data('opening',{my_progress:p_payload.progress})};});const p=c.reveal(1);c.reveal(2);c.reveal(5);c.reveal(10);d.resolve();await p;assert.deepEqual(calls,[1,10]);assert.equal(c.state.data.match.my_progress,10);});
test('a read started before a command cannot roll back locked action state',async()=>{const d=deferred();const {c}=harness(async(_,{p_action})=>p_action==='snapshot'?(await d.p,{data:data('battle')}):{data:data('battle',{action_locked:true})});const read=c.refresh();await c.matchCommand('turn_submit',{action:{kind:'attack'}});d.resolve();await read;assert.equal(c.state.data.match.action_locked,true);});
test('ready holds collection writes until both pack awards commit',async()=>{const {c,events,map}=harness(async()=>({data:data('clash',{my_ready:true})}));await c.matchCommand('ready');assert.equal(c.held,true);assert.ok(!events.includes('finish'));assert.equal(map.get('tcg-league-ready:qa'),'true');await c.accept(data('opening'),c.epoch);assert.equal(c.held,false);assert.equal(events.filter(x=>x==='finish').length,1);assert.equal(map.has('tcg-league-ready:qa'),false);});
test('uncertain commands retain the same receipt for retry, account epochs reject old response',async()=>{let calls=0,ids=[];const {c}=harness(async(_,{p_request_id})=>{ids.push(p_request_id);if(!calls++)throw Object.assign(Error('network'),{uncertain:true});return {data:data('battle',{action_locked:true})};});await assert.rejects(c.matchCommand('turn_submit',{action:{kind:'attack'}}));assert.ok(c.pending);await c.resume();assert.equal(ids.filter(Boolean)[0],ids.filter(Boolean).at(-1));assert.equal(c.pending,null);const old=c.state.data;await c.accept(data('result'),c.epoch-1);assert.equal(c.state.data,old);});
test('every high-rarity pack admits a squad without rerolls; normal budget preserves tradeoffs',()=>{const cards=Array.from({length:10},(_,i)=>({id:'sir-'+i,tier:5}));assert.equal(squadBudget(cards),150);assert.equal(validateDraft(cards,[0,1,2,3,4]),150);const mixed=[...cards.slice(0,5),...cards.slice(5).map(c=>({...c,tier:0}))];assert.equal(squadBudget(mixed),100);assert.throws(()=>validateDraft(mixed,[0,1,2,3,4]));assert.equal(battleStats(mixed[0]).power-battleStats({...mixed[0],tier:0}).power,3);assert.equal(ratingDelta(100,100,1),20);assert.equal(ratingDelta(100,500,1),28);});
test('competitive banner respects hidden records, earned server selection and escaping',()=>{const hidden=competitiveBanner({name:'<script>',rp:1000,show_record:false,trackers:['wins'],wins:999,banner:{frame:'diamond'},badges:['Master set']},()=>'<i>avatar</i>');assert.ok(!hidden.includes('999'));assert.ok(hidden.includes('&lt;script&gt;'));assert.ok(hidden.includes('Diamond'));const publicView=competitiveBanner({show_record:true,banner:{trackers:['draft_wins']},league_stats:{wins:7}},()=>'<i/>');assert.ok(publicView.includes('Draft Duel wins'));assert.ok(publicView.includes('>7<'));});
test('Realtime wakeups during a read coalesce into one fresh follow-up',async()=>{const first=deferred();let calls=0;const {c}=harness(async()=>{const n=++calls;if(n===1)await first.p;return {data:data('battle',{revision:n,action_locked:n>1})};});const read=c.refresh();c.refresh();c.refresh();first.resolve();await read;await new Promise(r=>setTimeout(r,0));assert.equal(calls,2);assert.equal(c.state.data.match.revision,2);});
test('snapshot failures back off automatic polling but manual reconnect can recover',async()=>{let calls=0;const {c}=harness(async()=>{calls++;throw Error('network');});await c.refresh();await c.refresh();await c.pulse();assert.equal(calls,1);c.client.rpc=async()=>({data:data('battle')});await c.resume();assert.equal(c.state.phase,'BATTLE');assert.equal(c.failures,0);});
test('account switches and disposal remove subscriptions/timers without accumulating listeners',async()=>{let created=0,removed=0;const timers=new Set(),client={rpc:async()=>({data:{...data('result'),user_id:'qa'}}),channel:()=>{created++;return {on(){return this;},subscribe(){return this;}};},removeChannel:()=>removed++};const clock={setTimeout,clearTimeout,setInterval:fn=>{timers.add(fn);return fn;},clearInterval:fn=>timers.delete(fn)};const c=new LeagueController({client,clock,storage:null});for(let i=0;i<10;i++){await c.setUser({id:'qa-'+i});assert.equal(timers.size,1);}c.dispose();assert.equal(timers.size,0);assert.equal(created,10);assert.equal(removed,10);await c.refresh();assert.equal(created,10);});

test('failed collection handoff preserves the reload recovery marker until a verified restore',async()=>{
 const {c,map}=harness(async()=>({data:data('opening')}));c.held=true;map.set('tcg-league-ready:qa','true');let fail=true;
 c.bridge.finish=async()=>{if(fail)throw Object.assign(Error('Collection sync pending'),{uncertain:true});};
 await assert.rejects(c.accept(data('opening'),c.epoch),/pending/);assert.equal(map.get('tcg-league-ready:qa'),'true');assert.equal(c.held,true);
 fail=false;await c.accept(data('opening'),c.epoch);assert.equal(c.held,false);assert.equal(map.has('tcg-league-ready:qa'),false);
});
test('same-account auth refresh preserves the visible duel, changing account closes it',async()=>{
 const {parseHTML}=await import('linkedom');const {installLeague}=await import('../src/league/index.js');const {window,document}=parseHTML('<html><body><div id="tradeHub"></div></body></html>');
 const api=installLeague({target:window,doc:document,client:null,bridge:{},hubRoot:document.getElementById('tradeHub'),hubView:{render(){}}});
 await api.setUser({id:'qa'});api.open();assert.equal(api.active(),true);await api.setUser({id:'qa'});assert.equal(api.active(),true);assert.equal(document.getElementById('collectorLeague').hidden,false);
 await api.setUser(null);assert.equal(api.active(),false);api.dispose();
});
