import {cardRows,filterCards,collectionValue,esc,money} from './model.js';
import {safeImage} from '../trade-hub/model.js';
export function installCollection(bridge,transactions,win=window,doc=document){
 const root=doc.getElementById('binder'),cardsPanel=root.querySelector('[data-binder-panel="binder"]');
 const gallery=doc.createElement('section');gallery.id='collectorGallery';gallery.className='collector-panel';cardsPanel.querySelector('.binder-studio-toolbar').after(gallery);
 const masters=doc.createElement('section');masters.dataset.binderPanel='master';masters.className='binderModeV147 collector-panel';root.append(masters);
 const sealed=doc.createElement('section');sealed.dataset.binderPanel='sealed';sealed.className='binderModeV147 collector-panel';sealed.innerHTML='<h2>Sealed collection</h2><p>Keep, display, inspect or open your sealed products.</p><button class="collector-button" id="collectorOpenSealed">OPEN SEALED SHELF</button>';root.append(sealed);sealed.querySelector('button').onclick=()=>doc.getElementById('openSealedMainV180')?.click();
 let query='',filter='all',sort='value',set='all',page=0,selectedSet=null,checklist=[],missing=false,masterPage=0,catalogRequest=0;
 const catalog=new Map();
 const art=c=>safeImage(c.thumb||c.img)?`<img loading="lazy" decoding="async" src="${esc(safeImage(c.thumb||c.img))}" alt="${esc(c.name)}">`:'<span class="collector-no-art">✦</span>';
 function renderCards(){
  const state=bridge.state(),all=cardRows(state),rows=filterCards(all,{query,filter,sort,set,chases:state.collectorV260?.chases||[]}),value=collectionValue(state,bridge.price,bridge.slabValue,bridge.sealedValue?.()||0);page=Math.max(0,Math.min(page,Math.ceil(rows.length/36)-1));
  doc.getElementById('binderStat').textContent=all.length+' identities · '+all.reduce((n,c)=>n+c.qty,0)+' copies across your collection';
  const focus=doc.activeElement?.id,start=doc.activeElement?.selectionStart;
  gallery.innerHTML=`<div class="collector-grid"><div class="collector-stat"><small>RAW CARDS</small><b>${money(value.raw)}</b></div><div class="collector-stat"><small>GRADED CARDS</small><b>${money(value.graded)}</b></div></div><div class="collector-stat"><small>SEALED · TOTAL COLLECTION</small><b>${money(value.sealed)} · ${money(value.total)}</b></div><p>All owned cards, including Bulk and escrow. Sealed products are included once, including items on display.</p><div class="collector-filters"><input id="collectorSearch" aria-label="Search all cards" placeholder="Name, set, number, rarity, variant…" value="${esc(query)}"><select id="collectorFilter" aria-label="Filter cards">${Object.entries({all:'All cards',new:'New discoveries',favourites:'Favourites',chases:'Chases',duplicates:'Duplicates',value:'High value',grade:'Grade candidates',listed:'Listed / escrow',locked:'Locked'}).map(([id,label])=>`<option value="${id}" ${id===filter?'selected':''}>${label}</option>`).join('')}</select><select id="collectorSort" aria-label="Sort collection">${['value','name','set','rarity','quantity','newest','need'].map(id=>`<option value="${id}" ${id===sort?'selected':''}>${id==='need'?'Master Set need':id.toUpperCase()}</option>`).join('')}</select><select id="collectorSet" aria-label="Filter set"><option value="all">All sets</option>${bridge.sets().map(s=>`<option value="${s.id}" ${s.id===set?'selected':''}>${esc(s.name)}</option>`).join('')}</select></div><p role="status">${rows.length} identities · ${all.reduce((n,c)=>n+c.qty,0)} copies owned</p><div class="collector-card-grid">${rows.slice(page*36,page*36+36).map(c=>`<button type="button" class="collector-tile" data-inspect-card="${esc(c.id)}">${art(c)}<b>${esc(c.name)}</b><small>${esc(c.set)} · ×${c.qty}</small><span>${money(c.market||c.raw)} ${c.locked?'🔒':''}${c.favourite?' ★':''}</span></button>`).join('')||'<p>No cards match. Rip a pack or change your filters.</p>'}</div><div class="collector-actions"><button class="collector-button" data-gallery-page="-1" ${page===0?'disabled':''}>Previous</button><span>Page ${page+1} / ${Math.max(1,Math.ceil(rows.length/36))}</span><button class="collector-button" data-gallery-page="1" ${(page+1)*36>=rows.length?'disabled':''}>Next</button></div>`;
  if(focus&&gallery.querySelector('#'+focus)){const input=doc.getElementById(focus);input.focus();if(input.setSelectionRange&&start!==null)try{input.setSelectionRange(start,start);}catch{}}
 }
 function renderMaster(){
  const totals=bridge.totals(),state=bridge.state(),sets=bridge.sets(),setInfo=sets.find(s=>s.id===selectedSet);
  if(!setInfo){masters.innerHTML=`<h2>Master Sets</h2><p>Every owned copy matters. Cards at grading, listed or in escrow still count.</p><div class="collector-grid">${sets.map(s=>{const t=totals[s.id],n=t?.owned.size||0,total=t?.total||0,p=total?Math.min(100,n/total*100):0;return `<button class="collector-set" data-master-set="${s.id}"><img loading="lazy" src="${esc(s.logo)}" alt=""><b>${esc(s.name)}</b><span>${n} / ${total||'checklist not loaded'} · ${p.toFixed(1)}%</span><progress value="${p}" max="100"></progress></button>`;}).join('')}</div>`;return;}
  const t=totals[selectedSet]||{owned:new Set(),total:0},total=Math.max(t.total,checklist.length),n=t.owned.size,p=total?Math.min(100,n/total*100):0,rows=checklist.filter(c=>!missing||!t.owned.has(c.id)),slabs=(state.gradingV44?.graded||[]).filter(c=>c.setId===selectedSet),graded8=new Set(slabs.filter(c=>c.grade>=8).map(c=>c.id)).size,graded10=new Set(slabs.filter(c=>c.grade>=10).map(c=>c.id)).size;
  const setValue=collectionValue(state,bridge.price,bridge.slabValue,0,selectedSet),best=cardRows(state).filter(c=>c.setId===selectedSet).sort((a,b)=>Number(b.market||b.raw||0)-Number(a.market||a.raw||0))[0];
  masters.innerHTML=`<button class="collector-button" data-master-back>← ALL SETS</button><img class="collector-master-logo" loading="lazy" src="${esc(setInfo.logo)}" alt="${esc(setInfo.name)} logo"><h2>${esc(setInfo.name)}</h2><div class="collector-grid"><div class="collector-stat"><small>SET COLLECTION VALUE</small><b>${money(setValue.total)}</b></div><div class="collector-stat"><small>BEST OWNED CARD</small><b>${esc(best?.name||'Your next discovery')}</b></div></div><p>${n} / ${total||'unknown'} unique cards · ${p.toFixed(1)}% complete · ${Math.max(0,total-n)} missing</p><progress value="${p}" max="100"></progress><div class="collector-actions">${[25,50,75,90,100].map(m=>`<button class="collector-button" data-master-reward="${m}" ${p<m||state.collectorV260.masterRewards[`${selectedSet}:${m}`]?'disabled':''}>${m}% · ${state.collectorV260.masterRewards[`${selectedSet}:${m}`]?'COLLECTED':{25:'$25 + 150 XP',50:'BADGE',75:'BINDER FINISH',90:'PROFILE TITLE',100:'TROPHY'}[m]}</button>`).join('')}</div>${p>=100?`<div class="collector-panel"><h3>Master Set+</h3><p>Grade collection: ${new Set(slabs.map(c=>c.id)).size} / ${total}<br>All graded 8+: ${graded8} / ${total}<br>Elite Master · all 10s: ${graded10} / ${total}</p><div class="collector-actions">${[['graded','GRADE COLLECTION',new Set(slabs.map(c=>c.id)).size],['elite','ALL GRADED 8+',graded8],['perfect','ELITE MASTER · ALL 10S',graded10]].map(([tier,label,count])=>`<button class="collector-button" data-master-plus="${tier}" ${count<total||state.collectorV260.masterPlus?.[selectedSet+':'+tier]?'disabled':''}>${label} · ${state.collectorV260.masterPlus?.[selectedSet+':'+tier]?'EARNED':'CLAIM TITLE & BADGE'}</button>`).join('')}</div><p>Variants are recorded where the source catalog distinguishes them. They never gate normal completion.</p></div>`:'<p>Complete the normal checklist to unlock Master Set+.</p>'}<div class="collector-actions"><button class="collector-button" data-master-missing>${missing?'SHOW ALL':'MISSING ONLY'}</button></div><p role="status" id="masterNotice"></p><div class="collector-card-grid">${rows.slice(masterPage*36,masterPage*36+36).map(c=>`<button class="collector-tile ${t.owned.has(c.id)?'owned':'missing'}" data-checklist-card="${esc(c.id)}">${art(c)}<b>${esc(c.name)}</b><small>#${esc(c.number)} · ${t.owned.has(c.id)?'OWNED':'MISSING'}</small></button>`).join('')||'<p>Checklist unavailable. Your saved progress is preserved.</p>'}</div><div class="collector-actions"><button class="collector-button" data-master-page="-1" ${masterPage===0?'disabled':''}>Previous</button><span>Page ${masterPage+1}</span><button class="collector-button" data-master-page="1" ${(masterPage+1)*36>=rows.length?'disabled':''}>Next</button></div>`;
 }
 async function loadSet(id){selectedSet=id;masterPage=0;const request=++catalogRequest;checklist=[];renderMaster();try{if(!catalog.has(id)){const r=await fetch(new URL(`catalog/${encodeURIComponent(id)}.json`,doc.baseURI));if(!r.ok)throw Error('Checklist temporarily unavailable');catalog.set(id,await r.json());}if(request!==catalogRequest)return;checklist=catalog.get(id);renderMaster();}catch(error){if(request===catalogRequest)masters.querySelector('#masterNotice').textContent=error.message;}}
 gallery.addEventListener('input',event=>{if(event.target.id==='collectorSearch'){query=event.target.value;page=0;renderCards();}});
 gallery.addEventListener('change',event=>{if(event.target.id==='collectorFilter')filter=event.target.value;if(event.target.id==='collectorSort')sort=event.target.value;if(event.target.id==='collectorSet')set=event.target.value;page=0;renderCards();});
 root.addEventListener('click',event=>{
  const b=event.target.closest('button');if(!b)return;
  if(b.dataset.inspectCard){const card=cardRows(bridge.state()).find(c=>c.id===b.dataset.inspectCard);win.tcgCardInspector.open(card,{source:card.binder?'binder':'bulk'});}
  if(b.dataset.galleryPage){page+=Number(b.dataset.galleryPage);renderCards();}
  if(b.dataset.masterSet)loadSet(b.dataset.masterSet);
  if(b.hasAttribute('data-master-back')){selectedSet=null;catalogRequest++;renderMaster();}
  if(b.dataset.checklistCard)win.tcgCardInspector.open(checklist.find(c=>c.id===b.dataset.checklistCard),{source:'checklist'});
  if(b.hasAttribute('data-master-missing')){missing=!missing;masterPage=0;renderMaster();}
  if(b.dataset.masterPage){masterPage+=Number(b.dataset.masterPage);renderMaster();}
  if(b.dataset.masterPlus)try{transactions.transact('masterPlus',{...transactions.review(),setId:selectedSet,tier:b.dataset.masterPlus});renderMaster();}catch(error){bridge.toast(error.message);}
  if(b.dataset.masterReward)try{transactions.transact('master',{...transactions.review(),setId:selectedSet,milestone:Number(b.dataset.masterReward)});renderMaster();}catch(error){bridge.toast(error.message);}
 });
 function refresh(){const route=win.tcgNavigation.snapshot();if(route.destination==='collection'){if(route.section==='cards')renderCards();if(route.section==='master')renderMaster();}}
 win.addEventListener('tcg:navigation',refresh);win.addEventListener('tcg:collector-updated',refresh);renderCards();renderMaster();return {refresh};
}
