import {districtOffer} from './district.js';
import {createCollectorClock} from './clock.js';
import {installCollectorNotifications} from './notifications.js';
import { CATALOG_COUNTS } from './catalog-counts.js';
import {migrateCollector,cardRows,collectionValue,journal,esc,money} from './model.js';
import {contractDay,refreshContracts} from './contracts.js';
import {createTransactions} from './transactions.js';
import {installCardInspector} from './inspector.js';
import {installCollection} from './collection.js';

export function installCollector(win=window,doc=document){
 if(win.tcgCollector)return win.tcgCollector;
 const bridge=win.tcgCollectorBridge;if(!bridge)throw Error('Collector bridge unavailable');
 win.tcgCollectorClock=createCollectorClock({account:bridge.account});
 const originalTotals=bridge.totals;bridge.totals=()=>{const totals=originalTotals();for(const [id,t] of Object.entries(totals))if(!t.total)t.total=CATALOG_COUNTS[id]||0;return totals;};
 const ensure=()=>{const state=bridge.state();if(migrateCollector(state))bridge.save();bridge.syncCosmetics?.();return state;};
 ensure();
 const notify=installCollectorNotifications(win,doc);
 const trophies=doc.getElementById('profile-panel-trophies'),progress=doc.getElementById('profile-panel-progress');
 if(trophies&&progress){while(trophies.firstChild)progress.append(trophies.firstChild);trophies.remove();}
 for(const id of ['profileChallengesSlot','profileMilestonesSlot','profileRankSlot']){const item=doc.getElementById(id)?.closest('details');if(item)progress?.append(item);}
 const profileTabs=doc.querySelector('.profileModeTabsV158');for(const tab of ['overview','progress','customise','stats']){const button=doc.getElementById('profile-tab-'+tab);if(button)profileTabs?.append(button);}
 const specials=doc.createElement('button');specials.className='collector-button';specials.textContent='SPECIAL COLLECTION';specials.onclick=()=>{win.setBinderModeV147?.('specials');};doc.querySelector('.binder-studio-toolbar')?.append(specials);
 const transactions=createTransactions(bridge),inspector=installCardInspector(bridge,transactions,win,doc),collection=installCollection(bridge,transactions,win,doc);
 doc.addEventListener('click',event=>{
  if(event.target.closest('#exchangeSellBulkV154')){event.preventDefault();event.stopImmediatePropagation();win.tcgNavigation.go('collection','bulk');doc.getElementById('sellBulkTubV64')?.click();return;}
  const sellSlab=event.target.closest('[data-sell-slab]');if(sellSlab){const card=bridge.state().gradingV44?.graded?.find(s=>s.uid===sellSlab.dataset.sellSlab);if(card){event.preventDefault();event.stopImmediatePropagation();doc.getElementById('gradeRevealV48')?.classList.remove('show');inspector.open(card,{source:'slab',slab:card});}return;}
  const grade=event.target.closest('[data-grade-inspect]');if(grade){const card=bridge.state().gradingV44?.submissions?.find(s=>s.uid===grade.dataset.gradeInspect);if(card){event.preventDefault();inspector.open(card,{source:'grading'});}}
  const slab=event.target.closest('.slabInspectV52');if(slab){const card=bridge.state().gradingV44?.graded?.find(s=>s.uid===slab.dataset.slabUid);if(card){event.preventDefault();event.stopImmediatePropagation();inspector.open(card,{source:'slab',slab:card});}}
 },true);
 for(const id of ['sellBulkAll','sellBulkOne']){const button=doc.getElementById(id);if(button)button.onclick=()=>{win.tcgNavigation.go('collection','bulk');doc.getElementById('sellBulkTubV64')?.click();};}
 const revealActions=doc.createElement('div');revealActions.className='collector-reveal-actions';revealActions.hidden=true;revealActions.innerHTML='<button class="collector-button" type="button">INSPECT CARD</button>';doc.getElementById('meta')?.append(revealActions);revealActions.querySelector('button').onclick=()=>inspector.open(win.TCG_PACK_LEGACY.currentCard(),{source:'reveal'});
 const contracts=doc.createElement('section');contracts.id='collectorContracts';contracts.className='collector-panel';doc.querySelector('.exchangeV154')?.prepend(contracts);
 const chases=doc.createElement('section');chases.id='pinnedChases';chases.className='collector-panel';doc.getElementById('rip').append(chases);
 const featured=doc.createElement('p');featured.id='collectorFeatured';featured.className='collector-featured';doc.querySelector('.rip-studio-header')?.after(featured);
 const journalPanel=doc.createElement('section');journalPanel.id='collectorJournal';journalPanel.className='collector-panel';journalPanel.hidden=true;doc.querySelector('[data-profile-panel-v160="stats"]')?.append(journalPanel);
 const journalButton=doc.createElement('button');journalButton.className='collector-button';journalButton.textContent='COLLECTOR JOURNAL';doc.querySelector('[data-profile-panel-v160="overview"]')?.append(journalButton);journalButton.onclick=()=>{win.tcgProfileStudio?.switchTab('stats');journalPanel.hidden=false;renderJournal();journalPanel.scrollIntoView({block:'start'});};
 const collectorStats=doc.createElement('section');collectorStats.id='collectorStatistics';collectorStats.className='collector-panel';doc.querySelector('[data-profile-panel-v160="stats"]')?.prepend(collectorStats);
 const dashboard=doc.createElement('section');dashboard.id='collectorDashboard';dashboard.className='collector-panel';doc.querySelector('[data-profile-panel-v160="overview"]')?.prepend(dashboard);
 function renderDashboard(){const s=ensure();const r=s.rankedV221||{},v260=s.collectorV260.stats,stats=[['PACKS OPENED',s.packs||0],['HITS',s.hits||0],['GOD PACKS',s.specialStatsV198?.godPacks||s.packStatsV253?.lifetimeGodPacks||0],['GRADED CARDS OWNED',s.gradingV44?.graded?.length||0],['GRADE 10S OWNED',(s.gradingV44?.graded||[]).filter(c=>c.grade>=10).length],['MARKET SALES',(s.marketV57?.sold||0)+(s.hubTotalsV256?.sales||0)],['TRADES',(s.tradeV154?.count||0)+(s.hubTotalsV256?.trades||0)],['RANKED WINS',r.wins||0],['RANKED LOSSES',r.losses||0],['WIN RATE',((r.wins||0)/Math.max(1,(r.wins||0)+(r.losses||0)+(r.ties||0))*100).toFixed(1)+'%'],['HIGHEST RP',r.seasonHigh||0],['CONTRACTS',v260.contracts||0],['10-PACKS SINCE V260',v260.tenPacks||0],['PACK VALUE SINCE V260',money(v260.packValue||0)]];collectorStats.innerHTML='<h2>Collector statistics</h2><div class="collector-grid">'+stats.map(([label,value])=>'<div class="collector-stat"><small>'+label+'</small><b>'+value+'</b></div>').join('')+'</div><details><summary>Legacy career</summary><p>Shop Rep: '+s.collectorV260.legacy.shopRep+' · rewards retained. Historical jobs and earnings remain in your save.</p></details>';const v=collectionValue(s,bridge.price,bridge.slabValue,bridge.sealedValue?.()||0),totals=Object.values(bridge.totals());dashboard.innerHTML=`<h2>Your collector world</h2><div class="collector-grid"><div class="collector-stat"><small>TOTAL COLLECTION</small><b>${money(v.total)}</b></div><div class="collector-stat"><small>MASTER SETS</small><b>${totals.filter(t=>t.total&&t.owned.size>=t.total).length}</b></div><div class="collector-stat"><small>PACKS OPENED</small><b>${s.packs||0}</b></div><div class="collector-stat"><small>CONTRACTS COMPLETED</small><b>${s.collectorV260.stats.contracts||0}</b></div></div><div class="collector-actions"><button class="collector-button" data-dashboard="rip">RIP A PACK</button><button class="collector-button" data-dashboard="collection">VIEW COLLECTION</button></div>`;dashboard.querySelectorAll('[data-dashboard]').forEach(b=>b.onclick=()=>win.tcgNavigation.go(b.dataset.dashboard));}
 function renderJournal(){const s=ensure();journalPanel.innerHTML=`<h2>Collector Journal</h2><p>Your significant pulls, milestones and collector transactions.</p>${s.collectorV260.journal.slice(0,40).map(e=>`<article class="collector-journal-event"><small>${new Date(e.time).toLocaleDateString()}</small><b>${esc(e.title)}</b>${e.value?`<span>${money(e.value)}</span>`:''}</article>`).join('')||'<p>Your next big discovery starts the journal. Earlier pack history is preserved.</p>'}`;}
 function renderContracts(){const state=ensure(),day=contractDay(state,bridge.now()),offers=refreshContracts(state,day);bridge.save();contracts.innerHTML=`<h2>Collector Contracts</h2><p>Daily and weekly requests put duplicate Bulk to work. Every delivery keeps one copy.</p><div class="collector-grid">${offers.map(c=>{const eligible=c.lines.every(l=>Number(state.bulkV64[l.id]?.qty)>l.qty&&!state.collectorV260.cards[l.id]?.locked);return `<article class="collector-panel"><small>${c.category} · expires Day ${c.expires+1}</small><h3>${esc(c.title)}</h3><p>${c.lines.map(l=>`${l.qty} × ${esc(state.bulkV64[l.id]?.name||l.id)}`).join('<br>')}</p><b>${money(c.cashCents/100)} + ${c.xp} XP</b><button class="collector-button" data-contract="${esc(c.id)}" ${c.claimed||!eligible?'disabled':''}>${c.claimed?'COMPLETED':eligible?'REVIEW DELIVERY':'MORE DUPLICATES NEEDED'}</button></article>`;}).join('')||'<p>Keep opening packs. Requests appear on the next game day once you have eligible duplicates.</p>'}</div><div id="contractReview" role="status"></div>`;}
 let contractReview=null;
 contracts.addEventListener('click',event=>{const b=event.target.closest('button');if(!b)return;if(b.dataset.contract){contractReview={...transactions.review(),contractId:b.dataset.contract};contracts.querySelector('#contractReview').innerHTML='<p>Deliver the displayed quantities? This removes those copies and pays the listed reward.</p><button class="collector-button" data-contract-confirm>CONFIRM DELIVERY</button>';return;}if(b.hasAttribute('data-contract-confirm'))try{transactions.transact('contract',contractReview);bridge.sound('coin');renderContracts();renderDashboard();}catch(error){contracts.querySelector('#contractReview').textContent=error.message;}});
 function renderChases(){const s=ensure(),owned=cardRows(s),set=bridge.selectedSet(),list=s.collectorV260.chases.filter(c=>c.setId===set);chases.hidden=!list.length;chases.innerHTML=`<small>YOUR CHASES</small><div class="collector-actions">${list.map(c=>`<button class="collector-button" data-chase-id="${esc(c.id)}">${esc(c.name)} · ${owned.some(x=>x.id===c.id)?'Owned ×'+owned.find(x=>x.id===c.id).qty:'Missing'}</button>`).join('')}</div>`;}
 chases.addEventListener('click',e=>{const b=e.target.closest('[data-chase-id]');if(b)inspector.open(ensure().collectorV260.chases.find(c=>c.id===b.dataset.chaseId));});
 let before=null,discovered=new Set(),revealed=new Set(),highest=0;
 win.addEventListener('tcg:pack-generated',()=>{const s=ensure();if(!before){before=new Map(Object.entries(bridge.totals()).map(([id,t])=>[id,{count:t.owned.size,total:t.total}]));discovered=new Set();revealed=new Set();highest=Math.max(0,...cardRows(s).map(c=>Number(c.market)||0));}});
 win.addEventListener('tcg:card-collected',event=>{const {card,wasNew}=event.detail||{};if(!card)return;const s=ensure();if(wasNew){discovered.add(card.id);s.collectorV260.cards[card.id]={...s.collectorV260.cards[card.id],discoveredAt:Date.now()};}bridge.save();});
 win.addEventListener('tcg:card-reveal',event=>{revealActions.hidden=false;const c=event.detail?.card;if(!c)return;const s=ensure();if(s.collectorV260.chases.some(x=>x.id===c.id)&&!revealed.has(c.id)){revealed.add(c.id);doc.getElementById('stage').classList.add('collector-chase-pull');notify('PINNED CHASE! '+c.name);bridge.sound('perfect');setTimeout(()=>doc.getElementById('stage')?.classList.remove('collector-chase-pull'),1800);journal(s,{id:'chase:'+s.packs+':'+c.id,kind:'chase',title:'Pinned chase · '+c.name,value:c.market});bridge.save();}});
 win.addEventListener('tcg:pack-summary',event=>queueMicrotask(()=>{
  revealActions.hidden=true;const detail=event.detail;if(!detail?.cards?.length)return;
  const wrap=doc.getElementById('v88Summary');if(!wrap)return;
  const rows=cardRows(ensure()),cards=detail.cards,t=bridge.totals()[detail.set.id],previous=before?.get(detail.set.id),fresh=discovered.size,best=[...cards].sort((a,b)=>Number(b.market)-Number(a.market))[0];
  const panel=doc.createElement('section');panel.className='collector-panel collector-smart-recap';panel.innerHTML=`<h2>Your pack, collected.</h2><div class="collector-grid"><div class="collector-stat"><small>NEW CARDS</small><b>${fresh}</b></div><div class="collector-stat"><small>DUPLICATES</small><b>${cards.length-fresh}</b></div><div class="collector-stat"><small>MASTER SET</small><b>${previous?.total?(previous.count/previous.total*100).toFixed(1)+'%':'—'} → ${t?.total?(t.owned.size/t.total*100).toFixed(1)+'%':'—'}</b></div><div class="collector-stat"><small>GRADE CANDIDATES</small><b>${cards.filter(c=>c.market>=5).length}</b></div></div><div class="collector-recap-cards">${cards.map((c,i)=>{const count=rows.find(r=>r.id===c.id)?.qty||1,tags=discovered.has(c.id)?'NEW · MASTER SET +1':count>1?'DUPLICATE ×'+count:'';return `<button class="collector-button" data-recap-card="${i}"><b>${esc(c.name)}</b><small>${tags}${safelyPinned(c)?' · CHASE':Number(c.market)>highest?' · PERSONAL BEST':Number(c.market)>=10?' · HIGH VALUE':''}</small></button>`;}).join('')}</div><p>Cards have been safely routed. Inspect a card to keep, grade, list, sell or move a copy.</p>`;
  wrap.querySelector('.collector-smart-recap')?.remove();wrap.querySelector('.v253Recap')?.append(panel);panel.querySelectorAll('[data-recap-card]').forEach(b=>b.onclick=()=>inspector.open(cards[Number(b.dataset.recapCard)]));
  const s=ensure();if(s.collectorV260.stats.lastRecap!==s.packs){s.collectorV260.stats.lastRecap=s.packs;s.collectorV260.stats.packValue=(s.collectorV260.stats.packValue||0)+cards.reduce((n,c)=>n+Number(c.market||0),0);if(detail.mode===10)s.collectorV260.stats.tenPacks=(s.collectorV260.stats.tenPacks||0)+1;}if(best.market>=10||detail.cards.some(c=>c.god))journal(s,{id:'pack:'+s.packs,kind:'pull',title:'Pulled '+best.name,value:best.market});bridge.save();before=null;renderChases();
 }));
 const safelyPinned=c=>ensure().collectorV260.chases.some(x=>x.id===c.id);
 function updateDay(){const state=ensure(),day=contractDay(state,bridge.now()),sets=bridge.sets().filter(s=>s.unlocked),meta=state.collectorV260;
  if(meta.featured?.day!==day){meta.featured={day,setId:sets[day%Math.max(1,sets.length)]?.id};bridge.save();}
  const set=sets.find(s=>s.id===meta.featured?.setId);featured.textContent=`DAY ${day+1} · FEATURED: ${set?.name||'Your next set'} · +5% PACK XP`;
  if(meta.contractRotation!==day)renderContracts();
  meta.seenSlabs??={};for(const slab of state.gradingV44?.graded||[]){if(meta.seenSlabs[slab.uid])continue;meta.seenSlabs[slab.uid]=true;if(slab.collectorV260){meta.stats.graded=(meta.stats.graded||0)+1;if(slab.grade>=10){journal(state,{id:'grade:'+slab.uid,kind:'grade',title:'Grade 10 · '+slab.name});notify('GRADE 10 · '+slab.name);}state.xp=Number(state.xp||0)+15;bridge.save();}}
 }
 win.addEventListener('tcg:navigation',()=>{ensure();renderChases();if(win.tcgNavigation.snapshot().destination==='profile'){renderDashboard();renderJournal();}if(win.tcgNavigation.snapshot().destination==='hub')renderContracts();updateDay();});
 win.addEventListener('tcg:set-selected',renderChases);win.addEventListener('tcg:collector-updated',event=>{renderChases();renderDashboard();for(const entry of event.detail?.events||[])notify(entry.title);});
 win.addEventListener('tcg:profile-updated',()=>{ensure();});
 win.addEventListener('tcg:hub-updated',event=>{const data=event.detail?.data;if(!data?.user_id||data.user_id!==bridge.account())return;win.tcgCollectorClock.accept(data.server_time,data.user_id);const s=ensure(),known=new Set(s.collectorV260.journal.map(e=>e.id));let changed=false;for(const activity of data.activity||[]){const id='hub:'+activity.id,d=activity.detail||{};if(known.has(id))continue;const important=['trade','trade_complete','battle_result'].includes(activity.kind)||['sold','purchase','bought'].includes(activity.kind)&&Number(d.price)>=1000;if(!important)continue;journal(s,{id,kind:activity.kind,time:new Date(activity.created_at).getTime(),title:activity.kind==='battle_result'?`Battle ${d.result||'completed'} · ${Number(d.delta||0)>=0?'+':''}${Number(d.delta||0)} RP`:activity.kind.replaceAll('_',' ')+' · '+(d.name||'Collector exchange'),value:Number(d.price||0)/100});changed=true;}if(changed){bridge.save();renderJournal();}});
 doc.addEventListener('click',event=>{if(event.target.closest('#studioChooseSet'))renderChases();});
 const timer=setInterval(()=>{if(!doc.hidden)updateDay();},30000);win.addEventListener('pagehide',event=>{if(!event.persisted)clearInterval(timer);});win.addEventListener('pageshow',event=>{if(event.persisted)updateDay();});
 updateDay();renderChases();renderDashboard();renderJournal();return win.tcgCollector={districtOffer:(key,generate)=>{const s=ensure(),offer=districtOffer(s,contractDay(s,bridge.now()),key,generate);bridge.save();return offer;},transactions,inspector,collection,notify,value:()=>collectionValue(bridge.state(),bridge.price,bridge.slabValue,bridge.sealedValue?.()||0),refresh:()=>{ensure();collection.refresh();renderChases();renderDashboard();}};
}
